liip_imagine:
  driver: "gd"

  loaders:
    articles_flysystem_loader:
      flysystem:
        filesystem_service: oneup_flysystem.uploads_articles_filesystem

  data_loader: articles_flysystem_loader

  resolvers:
    flysystem_resolver:
      flysystem:
        filesystem_service: oneup_flysystem.uploads_articles_filesystem
        root_url: '%article_uploads_url%'
        cache_prefix: media/cache
        visibility: public

  cache: flysystem_resolver

  filter_sets:
    author:
      quality: 75
      filters:
        thumbnail: { size: [ 480, 480 ], mode: outbound }
