POST https://127.0.0.1:8000/api/article/generate
Content-Type: application/json
Authorization: Bearer f77a093463986b0b6299757b70c832557418cf16

{
    "theme": "Fenris\\ThemeBundle\\Themes\\ProgrammingTheme",
    "title": "Заголовок",
    "keyword": "пирог",
    "declination": {
        "1": "пирога",
        "2": "пирогу",
        "3": "пирог",
        "4": "пирогом",
        "5": "пироге",
        "6": "пироги"
    },
    "sizeFrom": "3",
    "sizeTo": "5",
    "wordField": {
        "1": "слово",
        "2": "воробей"
    },
    "wordCountField": {
        "1": "3",
        "2": "5"
    }
}
